### ISSUE TITLE
Doesn't work in eclipse

### ISSUE THREAD

**Issue by isidore** [TeachingKidsProgramming/TeachingKidsProgramming.Java#10]
The code will not work in eclipse, gives a No class Def error for HttpUriRequest. Also the tkplauncher no longer opens the workspace correctly

**Comment by jamesrcounts** [comment]
I added some jars that should resolve the NoClassDef exceptions.  TkLauncher jar seems to be working fine when I tested it on a clean VM.

**Comment by lynnlangit** [comment]
Thank much


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by isidore** [comment]
NoClassDef is gone now, but displays a -HTTP/1.1 204 No Content

The Launcher still doesn't work (mac, haven't tested pc)

**Comment by jamesrcounts** [comment]
Katrina suggested the 204 response.  She said "so that clients wont complain".  I assume she meant restful clients.  Anyway, its what the new site sends on success.

Will try testing launcher on Mac.

**Comment by lynnlangit** [comment]
updated build process to include .jar files, also updated status message on upload via Virtual Proctor to be more user friendly.
